/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

export interface IAuthLoginRoutePostHandler {
  (request?: IAuthLoginRoutePostRequest): Promise<IAuthLoginRoutePostResponse>;
}

export interface IAuthLoginRoutePostRequest {
  session: any;
}

export interface IAuthLoginRoutePostResponse {
  statusCode: number;
}

