/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

export interface IAuthLoginRoutePostHandler {
  (request?: IAuthLoginRoutePostRequest): Promise<IAuthLoginRoutePostResponse>;
}

export interface IAuthLoginRoutePostRequest {
  body: IAuthLoginRoutePostRequestBody;
  session: any;
}

export interface IAuthLoginRoutePostResponse {
  body: IAuthLoginRoutePostResponseBody;
}

export interface IAuthLoginRoutePostRequestBody {
  email: string;
  password: string;
}

export interface IAuthLoginRoutePostResponseBody {
}

