/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

import * as http from 'http';
import * as url from 'url';

interface IPrivateGatewayClientOpts {
  url: string;
}

interface IPrivateGatewayClient {
  '/users': {
    post: IPrivateGatewayClientPostFunction;
  };
}

export interface IPrivateGatewayClientPostFunction {
  (request?: IPrivateGatewayClientPostRequest): Promise<IPrivateGatewayClientPostResponse>;
}

export interface IPrivateGatewayClientPostRequest {
  body: IPrivateGatewayClientPostRequestBody;
}

export interface IPrivateGatewayClientPostResponse {
  body: IPrivateGatewayClientPostResponseBody;
}

export interface IPrivateGatewayClientPostRequestBody {
  name: string;
}

export interface IPrivateGatewayClientPostResponseBody {
  id: string;
}

async function handler(req: any = {}, urlString: string = '', method = 'get'): Promise<any> {
  return new Promise((resolve, reject) => {
    try {
      const reqString = JSON.stringify(req.body || {});
      const urlParts = url.parse(urlString);
      
      const pathname = urlParts.pathname.replace(/(:[a-z][^\/]+)/gi, (a, b) => {
        return req.params[b.substr(1)] ? req.params[b.substr(1)] : b;
      });

      const input = http.request(
        {
          protocol: urlParts.protocol,
          host: urlParts.hostname,
          port: urlParts.port,
          path: pathname,
          method,
          headers: {
            'Content-Type': 'application/json',
            'Content-Length': Buffer.byteLength(reqString)
          }
        },
        output => {
          let responseString = '';

          output.on('data', chunk => {
            responseString += chunk;
          });

          output.on('end', () => {
            const responseBody = JSON.parse(responseString) || {};
            if (output.statusCode >= 200 || output.statusCode <= 299) {
              resolve({
                statusCode: output.statusCode,
                body: responseBody
              });
            } else {
              reject({
                statusCode: output.statusCode,
                body: responseBody
              });
            }
          });
        }
      );
      input.on('error', reject);
      input.write(reqString);
      input.end();
    } catch (error) {
      reject(error);
    }
  });
}

export class PrivateGatewayClient implements IPrivateGatewayClient {
  url = 'http://localhost:5000';

  constructor(opts?: IPrivateGatewayClientOpts) {
    if (opts && opts.url !== undefined) {
      this.url = opts.url;
    }
  }

  '/users': {
    post: IPrivateGatewayClientPostFunction;
  } = {
    post: async (req) => {
      return handler(req, `${this.url}/users`, 'post');
    }
  };
}
