/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

export interface ICreateRepoHandler {
  (request?: ICreateRepoRequest): Promise<ICreateRepoResponse>;
}

export interface ICreateRepoRequest {
  body: ICreateRepoRequestBody;
}

export interface ICreateRepoResponse {
  body: ICreateRepoResponseBody;
}

export interface ICreateRepoRequestBody {
  name: string;
}

export interface ICreateRepoResponseBody {
  id: string;
}

