/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

export interface IPostUsersHandler {
  (request?: IPostUsersRequest): Promise<IPostUsersResponse>;
}

export interface IPostUsersRequest {
  body: IPostUsersRequestBody;
}

export interface IPostUsersResponse {
  body: IPostUsersResponseBody;
}

export interface IPostUsersRequestBody {
  name: string;
}

export interface IPostUsersResponseBody {
  id: string;
}

