/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

export interface ICreateUserHandler {
  (request?: ICreateUserRequest): Promise<ICreateUserResponse>;
}

export interface ICreateUserRequest {
  email: string;
  password: string;
}

export interface ICreateUserResponse {
  id: string;
}

