/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

import { loadGatewayHandler } from 'marvelous';

import { IAuthLoginRoutePostHandler } from '../types';
import { AuthLoginRoutePost } from '../../routes';

export const authLoginRoutePostHandler: IAuthLoginRoutePostHandler = loadGatewayHandler(AuthLoginRoutePost);
