/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

import { loadGatewayHandler } from 'marvelous';

import { ICreateRepoHandler } from '../types';
import { CreateRepoOperation } from '../../operations';

export const createRepoHandler: ICreateRepoHandler = loadGatewayHandler(CreateRepoOperation);
