/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

import { loadGatewayHandler } from 'marvelous';

import { IPostUsersHandler } from '../types';
import { PostUsersOperation } from '../../operations';

export const postUsersHandler: IPostUsersHandler = loadGatewayHandler(PostUsersOperation);
