/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

import { loadGatewayHandler } from 'marvelous';

import { IPostAuthLoginHandler } from '../types';
import { PostAuthLoginOperation } from '../../operations';

export const postAuthLoginHandler: IPostAuthLoginHandler = loadGatewayHandler(PostAuthLoginOperation);
