/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

import { loadGatewayHandler } from 'marvelous';

import { IUsersRoutePostHandler } from '../types';
import { UsersRoutePost } from '../../routes';

export const usersRoutePostHandler: IUsersRoutePostHandler = loadGatewayHandler(UsersRoutePost);
