/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

import { loadHandler } from 'marvelous';

import { CreateUserMethodAction } from '../../actions';
import { ICreateUserMethodHandler } from '../types';

export const createUserMethodHandler: ICreateUserMethodHandler = loadHandler(CreateUserMethodAction);
