/*
 * this file is automatically generated for marvelous via zappjs
 * any manual changes to this file will be overwritten with the "mvs" command
 */

import { loadHandler } from 'marvelous';

import { CreateUserAction } from '../../actions';
import { ICreateUserHandler } from '../types';

export const createUserHandler: ICreateUserHandler = loadHandler(CreateUserAction);
